
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: 981813099174.dkr.ecr.ap-south-1.amazonaws.com/hello-repository:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: "service-helloworld"
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
